ServerEvents.recipes(event=>{
    remove_recipes_output(event,[
       "hexerei:pestle_and_mortar",
       "hexerei:mixing_cauldron",
       'hexerei:witch_hazel_broom',
       'hexerei:willow_broom',
       'hexerei:mahogany_broom'
    ]) 
})